household_power_consumption <- read.csv("~/R-programming/household_power_consumption.txt", header=TRUE,stringsAsFactors = FALSE, sep=";")
data<-subset(household_power_consumption,Date=="1/2/2007"|Date=="2/2/2007")
data[,2]<-paste(data[,1],data[,2])
time<-strptime(data[,2],format = "%d/%m/%Y %H:%M:%S")
data[,1]<-as.Date(data[,1])
Sys.setlocale("LC_ALL","English")
png(file="plot4.png")
par(mfrow=c(2,2),mar=c(6,4,2,2))
plot(time,data$Global_active_power,type = 'l',ylab = "Global Active power",pty="s",xlab='')
plot(time,data$Voltage,type = 'l',ylab = "Voltage",xlab="datetime",pty="s")
plot(time,data$Sub_metering_1, type= 'l',ylab = "Global Active power",xlab = '')
lines(time,data$Sub_metering_2,type='l',col="red")
lines(time,data$Sub_metering_3,type='l',col="blue")
legend("topright",col=c("Black","red","Blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_2"),lty=c(1,1),bty='n')
plot(time,data$Global_reactive_power,type = 'l',ylab = "Global_reactive_power",xlab="datetime",pty="s")
dev.off()