household_power_consumption <- read.csv("~/R-programming/household_power_consumption.txt", header=TRUE,stringsAsFactors = FALSE, sep=";")
data<-subset(household_power_consumption,Date=="1/2/2007"|Date=="2/2/2007")
data[,2]<-paste(data[,1],data[,2])
time<-strptime(data[,2],format = "%d/%m/%Y %H:%M:%S")
data[,1]<-as.Date(data[,1])
Sys.setlocale("LC_ALL","English")
png(file="plot2.png")
plot(time,data$Global_active_power,type = 'l',ylab = "Global Active power (kilowatts)",pty="s",xlab='')
dev.off()